### PR TITLE
Backport 0.14.4: automatically deactive span-based API

### PR DESCRIPTION
**Pull request by franzpoeschel**
This backports this PR: https://github.com/openPMD/openPMD-api/pull/1155

### CODE REVIEW

**Comment by ax3l** [comment]
Thank you, Franz! :)

Doesn't this depend on https://github.com/openPMD/openPMD-api/pull/1043 (which we do not backport to 0.14)?

**Comment by franzpoeschel** [comment]
> Doesn't this depend on [openPMD#1043](https://github.com/openPMD/openPMD-api/pull/1043) (which we do not backport to 0.14)?

Not strictly, I just originally put them in a linear order to avoid merge conflicts since they affected the same parts. Technically, they're independent though

**Comment by ax3l** [comment]
Perfect, thx! :)

**Comment by ax3l** [comment]
I'll add one more commit after merge to the changelog, so that we know this one got ported, too.

**Pull request merged**
